---

- include_tasks: install_additional_packages.yml
  tags: packages

- include_tasks: create_users_and_groups.yml

- include_tasks: setup_virtualenv.yml
  tags: virtualenv

- include_tasks: setup_git_repo.yml
  tags: deploy

- include_tasks: setup_django_app.yml
  tags: deploy

- include_tasks: setup_supervisor.yml
  tags: supervisor

- include_tasks: set_file_permissions.yml
  tags: deploy
