---
- name: Install security updates
  apt: default_release={{ ansible_distribution_release }}-security
       update_cache={{ update_apt_cache }}
       upgrade=dist
  tags:
    - packages
    - skip_ansible_lint

- name: Install pip
  apt: 
       name: python3-pip
       state: present
  tags:
    - packages
    - skip_ansible_lint

- name: Upgrade pip
  pip: name=pip state=latest
  tags:
    - packages
    - skip_ansible_lint
